//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTWNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CTDHs = new HashSet<CTDH>();
            this.CTGIAOHANGs = new HashSet<CTGIAOHANG>();
        }
    
        public int IDDH { get; set; }
        public Nullable<int> IDKH { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<int> TRANGTHAIDH { get; set; }
        public string PHUONGTHUCTHANHTOAN { get; set; }
        public string DIACHINHANHANG { get; set; }
        public string TRANGTHAIGH { get; set; }
        public string TENNGUOINHAN { get; set; }
        public Nullable<System.DateTime> NGAYGIAOHANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDH> CTDHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTGIAOHANG> CTGIAOHANGs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
