//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTWNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        public int IDFEEDBACK { get; set; }
        public Nullable<int> IDSP { get; set; }
        public Nullable<int> IDKH { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<int> POINTSTAR { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
