//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTWNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHAOSAT
    {
        public int IDKHAOSAT { get; set; }
        public string TENKHAOSAT { get; set; }
        public string NOIDUNG { get; set; }
        public string TRALOI { get; set; }
    }
}
